[env:ESP32]
platform = espressif32
; platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
; platform_packages = framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.3
framework = arduino
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv
; upload_port = COM5
upload_protocol = espota
; upload_port = 192.168.8.35
upload_port = 192.168.8.70
upload_flags =
  --auth=Balu
build_flags =
  -D TEST_SETUP
	; -DCORE_DEBUG_LEVEL=5
lib_deps =
	bodmer/TFT_eSPI@^2.4.79
  https://github.com/FrankBoesing/TFT_eSPI_ext

