[env:ESP32]
platform = espressif32
framework = arduino
board = az-delivery-devkit-v4
; upload_port = COM6
upload_protocol = espota
upload_port = <YOUR IP>
upload_flags =
  --auth = <YOUR PASS>
lib_deps =
	bodmer/TFT_eSPI@^2.4.70
