[env:ESP32]
platform = espressif32
framework = arduino
board = az-delivery-devkit-v4
; upload_port = COM6
upload_protocol = espota
upload_port = 192.168.8.35
; upload_port = 192.168.8.170
upload_flags =
  --auth=Balu
build_flags =
  -D DEBUG
lib_deps =
	bodmer/TFT_eSPI@^2.4.70
