{
 "title": "Smartmeter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Phase", "query": "L1, L2, L3" },
   { "name": "Rueckblick", "label": "Rückblick", "query": "7d,14d,30d,90d" }
  ]
 },
 "panels": [
  {
   "title": "Spannung",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "smartmeter.spannung.L1" },
    { "target": "smartmeter.spannung.L2" },
    { "target": "smartmeter.spannung.L3" }
   ]
  },
  {
   "title": "Strom",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "smartmeter.strom.L1" },
    { "target": "smartmeter.strom.L2" },
    { "target": "smartmeter.strom.L3" }
   ]
  },
  {
   "title": "cos(φ)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "smartmeter.cosphi" }
   ]
  },
  {
   "title": "P Bezug",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "smartmeter.momentanleistung.plus"
    }
   ]
  },
  {
   "title": "Energie gesamt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "smartmeter.wirkenergie.plus" }
   ]
  },
  {
   "title": "Verbrauch 1h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  { "title": "Uhrzeit", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 } },
  {
   "title": "Energieverbrauch der letzten $Rueckblick",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Strom",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "target": "smartmeter.strom.$Phase" }
   ]
  },
  {
   "title": "Energieverbrauch Stündlich",
   "type": "barchart",
   "description": "Verbrauch (Balken) = Intervall von angezeigter Zeit + 1h",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Spannung",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "target": "smartmeter.spannung.$Phase" }
   ]
  },
  {
   "title": "Energieverbrauch der letzten 90 Tage",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Blindleistungleistung Bezug",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    { "target": "smartmeter.cosphi" },
    { "expression": "(($A/$B)**2-($A)**2)**(1/2)", "type": "math" }
   ]
  },
  {
   "title": "Energieverbrauch Stündlich",
   "type": "neocat-cal-heatmap-panel",
   "description": "Verbrauch (Balken) = Intervall von angezeigter Zeit + 1h",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Wirk-& Blindleistung Bezug",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "target": "smartmeter.momentanleistung.plus"
    },
    { "expression": "(($A/$B)**2-($A)**2)**(1/2)", "type": "math" }
   ]
  }
 ]
}